---
- name: Upload SSH key for builder instance
  local_action:
    module: ec2_key
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    key_material: "{{ item }}"
    name: "{{ ami_builder_key_name }}"
    region: "{{ aws_region | default(omit) }}"
    wait: yes
  with_file: "{{ ami_builder_key_file }}"

- name: Create temporary instance to build AMI
  local_action:
    module: ec2
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    count: 1
    image: "{{ ami_builder_base }}"
    instance_tags: "{{ ami_builder_tags }}"
    instance_type: "{{ ami_builder_instance_type }}"
    key_name: "{{ ami_builder_key_name }}"
    region: "{{ aws_region }}"
    state: present
    wait: yes
    wait_timeout: 300
  register: ami_instance

- name: Add AMI builder instance to 'amibuilder' host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: amibuilder
  with_items: "{{ ami_instance.instances }}"

- name: Wait for builder instance to be accessible
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    timeout: 300
    state: started
  with_items: "{{ ami_instance.instances }}"
